# 내장함수 - 날짜/시간 함수
# ADDDATE/SUBDATE(날짜, 차이) : 날짜를 기준으로 차이만큼 일(DATE)을 더한/뺀 날짜를 반환
SELECT ADDDATE("2025-02-27 13:00:00", 2);
SELECT ADDDATE(NOW(), 14);
SELECT SUBDATE(NOW(), 14);
# ADDTIME/SUBTIME(날짜/시간, 차이) : 날짜/시간을 기준으로 차이만큼 시간을 더한/뺀 날짜/시간을 반환
SELECT ADDTIME(NOW(), "2:00:00");
SELECT SUBTIME(NOW(), "00:10:00");
# YEAR/MONTH/DAY(날짜) : 날짜에서 년/월/일을 구함
SELECT YEAR(NOW()) AS YEAR, MONTH(NOW()) AS MONTH, DAY(NOW()) AS DAY;
# HOUR/MINUTE/SECOND/MICROSECOND(시간) : 시간에서 시/분/초/마이크로초를 반환
SELECT HOUR(NOW()) AS HOUR, MINUTE(NOW()) AS MINUTE, SECOND(NOW()) AS SECOND, MICROSECOND(NOW(6)) AS MICROSECOND, MICROSECOND("2025-02-27 10:09:03.123") AS MICROSECOND; #NOW(6) : 마이크로초 6자리를 저장
# DATE/TIME(날짜) : 날짜에서 년-월-일/시:분:초를 반환
SELECT DATE(NOW()) AS DATE, TIME(NOW()) AS TIME;
# DATEDIFF(날짜1, 날짜2) : 날짜1에서 날짜2의 차이를 일로 반환. 날짜1 - 날짜2
SELECT DATEDIFF(NOW(), "2025-02-26 13:00:00") AS DATEDIFF;
# TIMEDIFF(날짜1/시간1, 날짜2/시간2) : 날짜1/시간1에서 날짜2/시간2의 차이를 시간:분:초로 반환
SELECT TIMEDIFF(NOW(), "2025-02-26 13:00:00") AS TIMEDIFF;
# NOW()/SYSDATE() : 현재 날짜와 시간을 반환
SELECT NOW(), SYSDATE();
# DATE_ADD/DATE_SUB(기준날짜, INTERVAL 간격 종류) : 기준 날짜에서 INTERVAL만큼 더한/뺀 날짜
# INTERVAL 종류
# YEAR/MONTH/DAY/HOUR/MINUTE/SECOND/MICROSECOND/QUARTER/WEEK
# YEAR_MONTH/DAY_HOUR/DAY_MINUTE/DAY_MICROSECOND A_B => A에서 B까지의 시간들
SELECT DATE_ADD(NOW(), INTERVAL 1 DAY) AS DATE_ADD_DAY;
SELECT DATE_ADD(NOW(), INTERVAL 1 QUARTER) AS DATE_ADD_QUARTER;
SELECT DATE_ADD(NOW(), INTERVAL 1 WEEK) AS DATE_ADD_WEEK;
SELECT DATE_ADD(NOW(), INTERVAL "1 1" YEAR_MONTH) AS DATE_ADD_YEAR_MONTH;
SELECT DATE_ADD(NOW(), INTERVAL "1 1" DAY_MICROSECOND) AS DATE_ADD_DAY_MICRO;

# 수학 함수
# ABS(숫자) : 절대값
# CEIL(숫자) : 소수점 첫번째 자리 올림
# FLOOR(숫자) : 소수점 첫번째 자리 내림
# ROUND(숫자) : 소수점 첫번째 자리 반올림
# ROUND(숫자, N) : N+1번째 자리에서 반올림
SELECT ABS(1), ABS(-1);
SELECT CEIL(1.49), FLOOR(1.49), ROUND(1.49);
SELECT CEIL(1.59), FLOOR(1.59), ROUND(1.59);
SELECT ROUND(1.49, 1) AS ROUND;